#!/usr/bin/perl
#
# Add a Comm2 field to a ROM 2.4x pfile
#
# -Eo's version-
#

$pfile = @ARGV[0];
$toadd = @ARGV[1];
print ("addstat: opening player file\n");
open (PFIN, "./$pfile");
open (PFOUT, ">./$pfile.foo");

readline:
 chop ($inline = <PFIN>);
 goto close if (eof);
 goto found if (substr($inline,0,4) eq "Comm");

writeline:
 print PFOUT ("$inline\n");
 goto readline;

found:
 print ("addstat: found COMM bitvector. Adding new bitvector.\n");
 $ca_out = "";
 $cb_out = "";
 $count = length( $inline );
 until ( $count == 0 )
 {
  $char = substr ($inline, $count, 1);
  $ca_out = ($ca_out . $char) if ($char ge "A" && $char le "Z");
  else
   $cb_out = ($cb_out . $char) if ($char ge "a" && $char le "a");
  else
   print ("addstat: error in COMM flags: $char\n\r");
  $count--;
 }
$inline = ("Comm $ca_out\nComm2 $cb_out\n");
goto writeline;

close:
 close PFIN;
 close PFOUT;
 print ("addstat: all done.\n");
 goto end;

end:
